<?php if (isset($flash)): ?>
  <?php foreach ($flash as $key => $messages): ?>
    <?php if ($key === 'success'): ?>
      <?php foreach ($messages as $message): ?>
        <div style="color:green;">
          <h3><?= $message ?></h3>
        </div>
      <?php endforeach ?>
    <?php else: ?>
      <?php foreach ($messages as $message): ?>
        <div style="color:red;">
          <h3><?= $message ?></h3>
        </div>
      <?php endforeach ?>
    <?php endif ?>
  <?php endforeach ?>
<?php endif ?>
<h3>Вхід</h3>
<form action="/" method="post">
  <label>Email:
    <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
  </label>
  <input type="submit" value="Вхід">
</form>
<hr>
<a href="/users/new">Реєстрація</a>