<h3>Змінити дані користувача</h3>
<form action="/users/<?= $user['id'] ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div><label>Ім'я: <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>"></label></div>
    <p style="color: red;"><?= $errors['name'] ?></p>
    <div><label>Email: <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>"></label></div>
    <p style="color: red;"><?= $errors['email'] ?></p>
    <br>
    <input type="submit" value="Відправити">
</form>